before_script:
    - angr-test sync hard

### local
claripy:
    script: "angr-test claripy"
    tags: [angr]

lint:
    script: "angr-test lint"
    tags: [angr]

### first level
simuvex:
    script: "angr-test simuvex"
    tags: [angr]

angr:
    script: "angr-test angr"
    tags: [angr]

fidget:
    script: "angr-test fidget"
    tags: [angr]

angrop:
    script: "angr-test angrop"
    tags: [angr]

rex:
    script: "angr-test rex"
    tags: [angr]

colorguard:
    script: "angr-test colorguard"
    tags: [angr]

pwnrex:
    script: "angr-test pwnrex"
    tags: [angr]

docs:
    script: "angr-test docs"
    tags: [angr]

patcherex:
    script: "angr-test patcherex"
    tags: [angr]

### other levels
tracer:
    script: "angr-test tracer"
    tags: [angr]

topsecret:
    script: "angr-test top-secret"
    tags: [angr]

driller:
    script: "angr-test driller"
    tags: [angr]
