before_script:
    - angr-test sync hard

claripy:
    script: "angr-test claripy"
    tags:
        - "angr"

simuvex:
    script: "angr-test simuvex"
    tags:
        - "angr"

angr:
    script: "angr-test angr"
    tags:
        - "angr"

fidget:
    script: "angr-test fidget"
    tags:
        - "angr"

angrop:
    script: "angr-test angrop"
    tags:
        - "angr"

claripy_lint:
    script: "angr-test lint"
    tags:
        - "angr"
